#!/bin/bash

curl 'https://glidenumber.net/glide/public/search/search.jsp' \
  -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7' \
  -H 'Accept-Language: en-US,en;q=0.9,pt;q=0.8' \
  -H 'Cache-Control: max-age=0' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -b 'JSESSIONID=3B2BB7F76D93918F51314A566D384CE2' \
  -H 'DNT: 1' \
  -H 'Origin: https://glidenumber.net' \
  -H 'Referer: https://glidenumber.net/glide/public/search/search.jsp' \
  -H 'Sec-Fetch-Dest: document' \
  -H 'Sec-Fetch-Mode: navigate' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'Sec-Fetch-User: ?1' \
  -H 'Upgrade-Insecure-Requests: 1' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Chromium";v="136", "Google Chrome";v="136", "Not.A/Brand";v="99"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  --data-raw 'level1=BRA&events=FL&keywords=&ftoption=%26&fromyear=&frommonth=&fromday=&toyear=&tomonth=&today=&maxhits=25&sortby=0&go.x=Search&nStart=0&posted=0&process=0&X_Resolution=1920'
